<!doctype html>
<html class="no-js" lang="en">



<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>HYSUS</title>
    
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow" />
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.ico">
    <!-- CSS
	============================================ -->
    <!-- Bootstrap CSS -->
    <link rel="canonical" href="https://hysus.com/disclaimer" />
    <link rel="stylesheet" href="assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/plugins/slick.css">
    <link rel="stylesheet" href="assets/css/plugins/font-awesome.css">
    <link rel="stylesheet" href="assets/css/plugins/icomoon.css">
    <link rel="stylesheet" href="assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
    <div class="main-content">

        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <img src="assets/images/about/sun-01.svg" alt="Sun images"><span title="Light Mode"> Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <img src="assets/images/about/vector.svg" alt="Vector Images"><span title="Dark Mode"> Dark</span>
                    </a>
                </li>
            </ul>
        </div>
       <?php include 'header.php';?>

        <!-- Start Breadcrumb Area -->
        <div class="axil-breadcrumb-area breadcrumb-style-default pt--170 pb--70 theme-gradient">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="inner">
                            <ul class="axil-breadcrumb liststyle d-flex">
                                <li class="axil-breadcrumb-item"><a href="index.php">Home</a></li>
                                <li class="axil-breadcrumb-item active" aria-current="page">DISCLAIMER</li>
                            </ul>
                            <h5 class="axil-page-title">DISCLAIMER</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="shape-images">
                <i class="shape shape-1 icon icon-bcm-01"></i>
                <i class="shape shape-2 icon icon-bcm-02"></i>
                <i class="shape shape-3 icon icon-bcm-03"></i>
            </div>
        </div>
        <!-- End Breadcrumb Area -->

        <!-- Start Page Wrapper -->
        <main class="page-wrappper">

            <!-- Start Privacy Policy Area  -->
            <div class="privacy-policy-area ax-section-gap">
                <div class="container">
                    <section id="privacy-page" class="gr--whitesmoke pb-80 inner-page-hero division">
                <div class="container">
                     <h2 class="text-center">DISCLAIMER</h2>
<p class="mt-4">HYSUS DIGITAL hereby grants you access to www.hysus.com (“the Website”) and invites you to purchase the services offered here.</p>
<h3>Definitions and key terms</h3>
<p class="mt-3">To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as.</p>
<li class="mt-3">Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
<li class="mt-3">Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Hysus Digital Private Limited, 2nd Floor, Unit No-253, Spaze I-Tech Park Tower B2, 54, Badshahpur Sohna Rd Hwy, Sector 49, Gurugram, Haryana 122018, India that is responsible for your information under this Disclaimer.</li>
<li class="mt-3">Service: refers to the service provided by HYSUS DIGITAL as described in the relative terms (if available) and on this platform.</li>
<li class="mt-3">Website: HYSUS DIGITAL’s site, which can be accessed via this URL: www.hysus.com You: a person or entity that is registered with HYSUS DIGITAL to use the Services.</li>
<h3 class="mt-5">Limited liability</h3>
<p class="mt-4">HYSUS DIGITAL endeavours to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.</p>
<p>The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from HYSUS DIGITAL.</p>

<p>Particularly, all prices on the website are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.</p>
<p>HYSUS DIGITAL shall not bear any liability for hyperlinks to websites or services of third parties included on the website. From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.</p>
<p>Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.</p>
<h3>Links to Other Websites Disclaimer</h3>
<p>This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by HYSUS DIGITAL. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h3 class="mt-5">Errors and Omissions Disclaimer</h3>
<p class="mt-3">HYSUS DIGITAL is not responsible for any content, code or any other imprecision.</p>
<p>HYSUS DIGITAL does not provide warranties or guarantees.</p>
<p>In no event shall HYSUS DIGITAL be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. HYSUS DIGITAL reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
<h3>General Disclaimer</h3>
<p>The HYSUS DIGITAL Service and its contents are provided "as is" and "as available" without any warranty or 
    representations of any kind, whether express or implied. HYSUS DIGITAL is a distributor and not a publisher 
    of the content supplied by third parties; as such, HYSUS DIGITAL exercises no editorial control over such content
     and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, 
     service or merchandise provided through or accessible via the HYSUS DIGITAL Service. Without limiting the foregoing, HYSUS DIGITAL specifically disclaims all warranties and representations in any content transmitted on or in connection with the HYSUS DIGITAL Service or on sites that may appear as links on the HYSUS DIGITAL Service, or in the products provided as a part of, or otherwise in connection with, the HYSUS DIGITAL Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by HYSUS DIGITAL or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, HYSUS DIGITAL does not warrant that the HYSUS DIGITAL Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
<h3 class="mt-5">Your Consent</h3>
<p>We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.</p>
<h3 class="mt-3">Changes To Our Disclaimer</h3>
<p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be
     prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer.
      If you do not want to agree to this or any updated Disclaimer, you can delete your account.</p>
<h3>Contact Us</h3>
<p>Don't hesitate to contact us if you have any questions regarding this Disclaimer.</p>
<li>Via Email: hello@hysus.com</li>
<li>Via this Link: www.hysus.com/contact</li>
<!-- End row -->
                </div>     <!-- End container -->
            </section>
                </div>
            </div>
            <!-- End Privacy Policy Area  -->

        </main>
        <!-- End Page Wrapper -->

        <!-- Start Footer Area -->
        <?php include 'Footer.php';?>
        <!-- End Footer Area -->
    </div>
    <!-- JS
============================================ -->

    <!-- Modernizer JS -->
    <script src="assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="assets/js/vendor/bootstrap.min.js"></script>
    <script src="assets/js/waypoints.min.js"></script>
    <script src="assets/js/wow.js"></script>
    <script src="assets/js/counterup.js"></script>
    <script src="assets/js/imagesloaded.js"></script>
    <script src="assets/js/isotope.js"></script>
    <script src="assets/js/tilt.js"></script>
    <script src="assets/js/anime.js"></script>
    <script src="assets/js/tweenmax.js"></script>
    <script src="assets/js/slipting.js"></script>
    <script src="assets/js/scrollmagic.js"></script>
    <script src="assets/js/addindicators.js"></script>
    <script src="assets/js/slick.js"></script>
    <script src="assets/js/youtube.js"></script>
    <script src="assets/js/countdown.js"></script>
    <script src="assets/js/scrollup.js"></script>
    <script src="assets/js/stickysidebar.js"></script>
    <script src="assets/js/js.cookie.js"></script>
    <script src="assets/js/jquery.style.switcher.js"></script>
    <script src="assets/js/contactform.js"></script>
    <!-- Plugins JS -->
    <script src="assets/js/plugins/plugins.min.js"></script>
    <!-- Main JS -->
    <script src="assets/js/main.js"></script>
   <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="bd26f25e-cbc2-45bb-93cc-c8222cd13b1b";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

</body>



</html>